version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run: docker build -t globau/conduit-autoland-treestatus:$CIRCLE_BRANCH .
     - run: docker push globau/conduit-autoland-treestatus:$CIRCLE_BRANCH
