version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run: |
          printf '{"commit":"%s","version":"%s","source":"https://github.com/%s/%s","build":"%s"}\n' \
            "$CIRCLE_SHA1" "$CIRCLE_TAG" "$CIRCLE_PROJECT_USERNAME" "$CIRCLE_PROJECT_REPONAME" "$CIRCLE_BUILD_URL" \
            > version.json
          cat version.json
          cp version.json $CIRCLE_ARTIFACTS
     - run: |
          docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
          docker build -t globau/conduit-autoland-treestatus .
          docker push globau/conduit-autoland-treestatus
